# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Rating.destroy_all
RecipeSave.destroy_all
Comment.destroy_all
Ingredient.destroy_all
PrepStep.destroy_all
Recipe.destroy_all
User.destroy_all


User.create(email: "andhudhow@gmail.com", password: "password", nickname: "Andrew H.")
10.times do
  User.create(email: Faker::Internet.email, password: Faker::Beer.brand, nickname: Faker::Kpop.girl_groups)
end

# 25.times do
#   Recipe.create(title: Faker::Food.sushi, author_name: Faker::Kpop.solo, description: Faker::Food.description + " " + Faker::Food.description + " " + Faker::Food.description, servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
# end

prep_step_options = ["Place the pork in a large, shallow bowl. Mix the white sugar and 1 cup of the salt together in another bowl, then rub the mixture all over the meat. Cover it with plastic wrap and place in the refrigerator for at least 6 hours, or overnight.",
                      "When you're ready to cook, heat oven to 300. Remove pork from refrigerator and discard any juices. Place the pork in a roasting pan and set in the oven and cook for approximately 6 hours, or until it collapses, yielding easily to the tines of a fork. (After the first hour, baste hourly with pan juices.) At this point, you may remove the meat from the oven and allow it to rest for up to an hour.",
                      "Meanwhile, make the ginger-scallion sauce. In a large bowl, combine the scallions with the rest of the ingredients. Mix well and taste, adding salt if needed.",
                      "Make the ssam sauce. In a medium bowl, combine the chili pastes with the vinegar and oil, and mix well.",
                      "Prepare rice, wash lettuce and, if using, shuck the oysters. Put kimchi and sauces into serving bowls.",
                      "When your accompaniments are prepared and you are ready to serve the food, turn oven to 500. In a small bowl, stir together the remaining tablespoon of salt with the brown sugar. Rub this mixture all over the cooked pork. Place in oven for approximately 10 to 15 minutes, or until a dark caramel crust has developed on the meat. Serve hot, with the accompaniments.",
                      "Heat oven to 400 degrees. Peel the squash and cut it crosswise, separating the long neck from the bulbous bottom part. Slice the neck into 1/2-inch-thick dominoes; scoop out seeds from the bottom and slice the squash 1/2 inch thick.",
                      "Whisk together 2 tablespoons neutral oil, the soy sauce, brown sugar and gochujang or sambal oelek.",
                      "Place squash and mushrooms on one baking sheet, but do not mix them together. Place broccoli rabe on another baking sheet. Divide sauce between the two pans and use your hands to toss the vegetables so they’re evenly coated.",
                      "Transfer both pans to the oven. Cook broccoli rabe for 5 to 8 minutes, until collapsed and the thicker parts of the stems are tender. Cook mushrooms for 15 to 20 minutes, until juicy and slightly shrunken, and remove from baking sheet. Return squash to oven and cook 5 to 15 minutes longer, until caramelized and tender. Cover the vegetables with foil until ready to serve.",
                      "If you'd like, make crispy-base bibimbap rice: Just before serving, heat 1 tablespoon neutral oil and the sesame oil in a wide skillet over medium heat. Press rice into the skillet, making a thick cake. Let cook without disturbing for 4 to 5 minutes, until a golden brown crust forms on the bottom of the rice. (If you skip this step, use freshly cooked rice instead.)",
                      "While the crispy rice is cooking, fry the eggs: Heat a large skillet over medium-high heat. Add enough neutral oil to liberally coat pan. Crack in 2 eggs and sprinkle with salt. Tilt the pan so some of the oil runs over the edges of the egg whites, lower heat to medium-low and cook 1 minute. Sprinkle with about 1/4 teaspoon water (or soy sauce), cover and cook another minute, until whites are set. Carefully remove to a plate. Repeat with remaining eggs.",
                      "To serve, use a spatula to scoop out rice and divide it among 4 bowls, ensuring that everyone gets some of the crispy part. Top with vegetables, including any marinade left on the baking sheets, and place 1 fried egg on top of vegetables in each bowl. Garnish with sprouts or shoots, pickles (if using) and lime. Serve immediately, passing gochujang or sambal oelek at the table.",
                      "In a small bowl, prepare the dipping sauce. Whisk together 2 tablespoons of the soy sauce, 2 teaspoons of the rice wine vinegar and mirin. Set aside.",
                      "In another small bowl, combine the remaining 2 tablespoons soy sauce, the remaining 4 teaspoons rice wine vinegar, denjang or miso paste, garlic, ginger, egg yolk, 1 cup of water and mix well.",
                      "Heat a 10-inch skillet over medium-high heat with 1/4-inch grapeseed or vegetable oil. The oil should be hot, but not smoking, about 325 degrees.",
                      "In a large bowl, mix the rice flour, all-purpose flour and baking powder. Add the squid and scallions and toss to combine. Pour in the denjang mixture and stir until just combined, taking care not to overmix.",
                      "Carefully spoon half of the batter into the hot pan and fry until the bottom is golden and crispy, about 3 to 4 minutes. Flip and fry for another 3 to 4 minutes until crispy and cooked through. Transfer to a rimmed baking sheet lined with paper towels so oil can drain. Repeat with the second half of the batter. Cut pancakes in quarters and serve with the dipping sauce.",
                      "In a large bowl, stir together chili paste, ketchup, sugar, sesame seeds and lemon juice. Taste and adjust flavors to get a spicy-sweet-tangy finish. Set aside.",
                      "Working in batches to avoid crowding, lift chicken from marinade, dredge lightly in seasoned flour and cornstarch, gently drop into oil and fry for 5 to 7 minutes, turning occasionally, until golden brown and crisp. Drain on paper towels. Repeat with remaining chicken, checking oil temperature between batches.",
                      "Bring a large pot of water to a boil. Add about 1 teaspoon of the meat mixture to the center of a dumpling wrapper. Moisten edges of wrapper with a fingertip dipped in water. Fold over to create triangle or semicircle, depending on the shape of your wrappers. Gently pinch wrapper together using thumbs and forefingers so that the wrapper hugs the filling, checking that edges are aligned and sealed.",
                      "Drain the tofu and pat dry with paper towels. Cut into 1/2-inch-thick dominoes, blot again with paper towels and add to the bowl with the marinade. Gently toss to coat. Cover and refrigerate for 15 minutes to an hour, or for up to a day.",
                      "Mix together the rice vinegar, sesame oil, garlic, scallions, sesame seeds and salt to taste in a small bowl or measuring cup. Add red pepper paste if desired. Set aside.",
                      "Heat a wok or large, heavy skillet over medium-high heat until a drop of water evaporates immediately on contact and add the canola oil. Stir-fry the tofu for 3 to 5 minutes, until lightly browned, and remove to a plate. Add the shiitakes to the pan, let sit without stirring for 1 minute, then stir-fry for another minute or two, until tender. Remove to a plate.",
                      "Fry the eggs in the hot pan or in a separate nonstick skillet until the whites are set and the yolks are still runny. Season with salt and pepper.",
                      "In separate bowls, toss the prepared daikon and carrots with salt to taste and cover with cold water. Soak for 15 to 30 minutes. Drain and squeeze dry. Place in separate bowls and toss each with 1 tablespoon of the vinegar and sesame oil mixture. Add salt or soy sauce to taste. Set aside in the refrigerator.",
                      "Combine the wine, water, crushed garlic, ginger, scallions and dried chili pepper in a lidded pot or pan and bring to a boil. Add the clams, cover and steam until they open, about 3 minutes. Using tongs, remove the clams to a bowl, cover and keep warm. Strain the liquid in the pot through a cheesecloth-lined strainer set over a bowl and return to the pan. Add the sugar, soy sauce, sesame oil and any liquid that has accumulated in the bowl with the clams, and bring to a boil. Reduce to about 1/2 to 1/3 cup and remove from the heat.",
                      "Add the chili paste to the cabbage along with the scallions, garlic, ginger and, if you like, the carrot sticks. Mix the kimchi well and pack it into hard plastic or glass containers. Pour in enough of the brine to cover the vegetables.",
                      "In a medium bowl, whisk eggs just until frothy. Add flour and salt and whisk to combine. Add vegetables or meat and stir to blend. Add 1/2 cup ice water and mix again to blend.",
                      "In a food processor, combine garlic, pear, onion and ginger and process until very smooth and creamy, about 1 minute.",
                      "In a bowl or sealable plastic bag, combine steak, marinade, scallion, soy sauce, sesame oil, brown sugar and pepper and mix well. Cover or seal, then refrigerate at least 30 minutes or overnight.",
                      "Place a wok or large sauté pan over high heat, add peanut oil, and swirl to coat the entire wok or pan. When the oil is shimmering, add the cabbage and carrot and cook until tender, stirring occasionally, 1 to 3 minutes."]

comment_options = ["Delicious! Made with red miso and loved it! Next time, though, I will drop by the spoonful to make multiple small pancakes (~3-4 inches) rather than a single big one. Done en masse, it disintegrated on flipping and threatened to burn on the outer edges before the center was fully done.",
                    "I have made these and put in shredded carrots, peas, or whatever veggies I have available. The more the merrier. When I lived in Korea, these pancakes were traditionally served in the mountainous areas. When climbing, one would come upon a set up where they were being made and it was a nice rest time. The amazing part was that they got the whole deal up the mountain along with cases of soda. And I was usually gasping for air.",
                    "first time I made this, the batter was too thick, so I've reduced the amount of flour (rice and normal) to about 2/3, and added water mixture to the consistency I like. Also I used Go-chu-jang (Korean red pepper paste) instead of Den-Jang, which added tangier taste. And
                    made smaller patties.I think it got better.",
                    "If I made this again, I'd chop squid or shrimp and scallions finely, and reduce flour, to make a thinner batter w ingredients that cooked thru faster.",
                    "Using all AP flour will give you a softer and possibly slightly soggier coating, but it should work in terms of holding everything together. If you try it let us know.",
                    "Cook until they begin to sizzle, then transfer to oven. Roast until brown on one side, then shake pan to redistribute. Remove when bright green but browned and fairly tender, about 10 to 15 minutes. Meanwhile, purée kimchi in food processor or blender until fairly smooth.",
                    "Return pan to stove over medium heat and stir in butter, salt and pepper, and bacon. Put kimchi in bottom of a bowl and top with sprouts. Spoon a little kimchi juice over all and serve.",
                    "This is really good and fast to make. Only thing I will say is the soup base is not red like the picture. I think maybe if I do this recipe again I’ll add some sun dried tomatoes or a little tomato paste.",
                    "Yes, there are different kinds of white miso just as there are different brands/makers of miso and all have different amounts of sodium. Check labels to find low sodium varieties or use smaller amounts in your recipes.",
                    "I've investigated the matter of substituting gochujang for tomato paste. I have concluded that you can and you should.",
                    "Similar to my mom's fantastic Korean-style barbecue marinade, but missing one crucial flavor! Add maybe a tablespoon of toasted sesame seed oil.",
                    "Easy and tasty. Served with white rice. Put everything on a bed of raw baby spinach sprinkled with fresh lime juice. Used hot pepper jelly as a condiment.",
                    "The low sodium Kikkoman soy sauce has a better flavor, in my opinion.",
                    "Thought it needed more flavor. Next time I do this, if I do, I’ll add more salt or soy sauce, and would consider adding red pepper flakes and ginger.",
                    "This was easy and great. Was very flavorful, unlike another reviewer. If we had to change anything, we would halve the salt.",
                    "I am old but new to some cooking! Why bake meatballs and not broil? I have tried the basic meatball recipe here and it calls for broiling. I like the crispy top!",
                    "No Korean red pepper paste?? No beef at our house so will try with dark ground turkey or chicken. Thanks!!",
                    "Any thoughts on cooking these in a slow cooker or an electric skillet? I live in a warm environment and the thought of even turning the oven on makes me sweat.",
                    "This ain’t a recipe worth trying. How about incorporating diced kimchi or something interesting so it’s not hamburger, ritz and soy sauce. Nah.Gonna.Do-it.",
                    "Used ground turkey instead of beef and panko in place of ritz crackers. Very good.",
                    "Double veggies at least. Add dash fish sauce and salt and pepper. More sesame oil.",
                    "I think this sauce benefitted from about a T of vinegar. Used it in Korean Pork tacos. Delicious!",
                    "I made this using miso which is very similar to the Doenjang . My husband is a beekeeper so I used our honey but any medium flavored honey will do. Very easy and very very tasty.",
                    "And if you're dead-set against SPAM, diced, cooked Portuguese sausage (linguica) or even bacon work great, too.",
                    "If you're in/near New Jersey, try it with pork roll.",
                    "Added garlic, diced carrot and bell pepper, sliced mushrooms. Didn't have any leftover meat, so this version vegetarian. Good!",
                    "This is completely addictive. Make as written. Do not substitute. You won't be sorry. You will only contemplate how empty your life was before this recipe.",
                    "As a full-fledged Korean, I can tell you this recipe is the bomb! Soy sauce is unnecessary, as you get plenty of salt from the kimchee and nori. It's good to cook this in a cast-iron pan so you get the crunchy goodness on the bottom. Even better with a drizzle of sriracha sauce at the end! Yum!",
                    "Where's the gochujang in this recipe?? Gotta have gochujang in your kimchee fried rice.",
                    "Having lived in N.J. for over 30 years I also recommend 'turkey ham' and/or a bit of liquid smoke if you cannot find Spam.",
                    "Turkey pepporoni works great instead of the Spam and is relatively healthy. Monty Python ruined Spam forever!!",
                    "Used Pork belly for a richer flavor. Also, caramelized the kimchi on low heat for about 15 minutes to bring a spicy sweetness to the dish.",
                    "I’m sorry but I can’t cook with coke. That’s absurd. I’ll find a substitute liquid. Otherwise it looks like a great recipe.",
                    "A grapefruit spoon works even better - the serrated tip makes short work of the insides of any pepper.",
                    "If the jalapenos are too hot, drop them in boiling water that has a tablespoon of brown sugar dissolved in it and boil for about one minute. Drain and continue.",
                    "This is a wonderfully delicious recipe! I opted to throw these into an Instant Pot pressure cooker since no grill and I didn't want to smoke up the house with the broiler. 20 mins at high pressure and natural release and they literally were falling off the bone and melt in your mouth tender. It's a different way to cook them if you can't broil or grill but have an instant pot --- the rest of the recipe stays essentially the same. Next time, I'll grill them!",
                    "I find that the pear puree is really unique and provides a sweet flavor that sugar cannot replicate. I'd say keep the pear and skip the sugar!",
                    "These types of ribs, called kalbi, are very popular here in Hawaii. The exact portions on the marinade are not too important. I use green onions instead of the regular onion, and any type of white wine. You can skip the sugar, and the ribs turn out just fine. You don't even need to purée the marinade if you don't want to. For me, the real trick is equal parts of soy sauce and white wine.",
                    "Skip the pear puree - it's mushy, overkill, and unnecessary. Otherwise a great and easy recipe.",
                    "To tenderize, try using a bit of kiwi instead. That's what my mom usually does.",
                    "These were the best short ribs I've ever had. They were absolutely delicious.",
                    "Very delicious and, if you have access to fresh dumplings as we do here in San Francisco, it’s a snap to make. I disagree with adding the beef so early tho. Thinly sliced beef should be added at the end of cooking time, otherwise it becomes leathery.",
                    "How would this recipe change if you used a slower cooker instead?",
                    "With only stove and oven, which would be better, stovetop in a dutch oven or oven roasted covered? If stovetop is better, how long to cook in dutch oven? If oven is better, at what temp and for how long? Thanks.",
                    "Cook for 5 to 7 hours in a slow cooker.",
                    "90 min seems like a lot of time in pressure cooker. I'd definitely reduce the time to maybe 50 min.",
                    "You can just put this in a dutch oven at 250 for about five hours.",
                    "Pork can also be prepared in a slow cooker set to 5 to 7 hours on high.",
                    "I highly recommend at least an overnight marinate with the rub. I've done pork shoulders in the oven at 200F for the day and find that the meat is more evenly flavored . This is especially important if you don't intend to shred it which I don't like to do. It's just more enjoyable to pull apart at the table. Resting it and putting it under the broiler whole would be my choice. You can inject the sauce too.",
                    "I've made this a few times and was convinced by the comments one time to reduce the coming time, which turned out to be a mistake. Trust Melissa and stick with 90 minutes.",
                    "90 minutes on high was perfect what are you guys talking about with this 60 minutes business?"]

recipe1 = Recipe.create(title: "Jajangmyeon", author_name: Faker::Kpop.solo, description: "This dish is a Koreanified take on the fried sauce noodles served in the Shandong province of China. It occupies a similar place in Korean cuisine to the one General Tso’s chicken has in American food: a birth-country meal translated to accommodate the too-tired-to-cook takeout tastes of a host nation. It is milder than the Chinese original, a little more porky, the sort of dish you’ll have people asking you to make once or twice a month. You’ll need thick white-wheat noodles, like udon, and some of the Korean black-bean paste known as chunjang, available at Korean markets and online. If you can’t find pickled daikon to serve as a garnish, some raw onions dressed in vinegar will make a fine alternative.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe2 = Recipe.create(title: "Scallion Pancakes With Squid", author_name: Faker::Kpop.solo, description: "The textures in this delicious recipe for pajeon, traditional Korean scallion-based pancakes, are manifold: meaty from the squid, crunchy yielding to soft from the fried bits of batter, juicy from the scallion. It came to The Times from Hooni Kim, the chef at Hanjan in Manhattan. One of the secrets to this pancake is waiting for the oil to heat up before mixing the batter. That way, the batter doesn’t sit around and turn gluey. Eat them as hot as you can without burning your fingers. The risk is worth it.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe3 = Recipe.create(title: "Cold Spicy Kimchi Noodles", author_name: Faker::Kpop.solo, description: "Could this be the anti-ramen? Either way, it’s my new favorite cold pasta, custom-made for hot summer weather because it is refreshingly and unapologetically spicy. Make the sauce in advance, but wait to toss with the noodles until just before serving. While you could order Korean ingredients online, it’s more fun to go to a Korean supermarket, if only to see all the different types of kimchi. Korean red pepper flakes are without seeds, and only medium hot, so you can use a lot.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe5 = Recipe.create(title: "Mung Bean Pancakes", author_name: Faker::Kpop.solo, description: "In Korea and many other Asian countries, the holiday season is not over until after the lunar New Year, which falls on January 25 this year. Called Seollal (설날) in Korea, it’s one of the two most celebrated traditional holidays. Along with tteokguk (떡국, rice cake soup), nokdujeon (녹두전) is a must for the New Year’s Day feast.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe6 = Recipe.create(title: "Samgyetang (Ginseng Chicken Soup)", author_name: Faker::Kpop.solo, description: "This is a traditional Korean soup consumed on the hottest days of summer. Fancier Korean restaurants will often add extra medicinal herbs and aromatics, but the home-cooked, mom-approved samgyetang that Koreans know best has six indispensable ingredients: chicken, garlic, scallions, glutinous rice, ginseng (fresh is preferred) and dried red dates (jujubes). The last three items may be hard to find, but every Korean grocery stocks them. Many shops even sell samgyetang-stuffing kits, which come with a small packet of rice, a couple of dried jujubes and a nub of dried ginseng, with some brands offering additional, often arcanely named aromatics (like milkvetch root or acanthopanax) to fortify the broth. The soup is normally prepared for one, with a single small chicken or Cornish hen served whole in boiling broth.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe7 = Recipe.create(title: "Cheese Buldak (Fire Chicken)", author_name: Faker::Kpop.solo, description: "Cheese buldak is a Korean dish that is incredibly easy to prepare: a marinade of red-pepper paste and red-pepper flakes that becomes a fiery sauce for braised chicken, which is then served beneath a cloak of broiler-melted mozzarella. A child could do it, or an adult who often acts like one. Mine is an adaptation of a recipe that owes its deepest debt to Emily Kim, the Korean web star known as Maangchi, whose video for cheese buldak has been viewed on YouTube more than seven million times. (Omit the rice cakes if you can’t find them easily!) Thanks to subtitling by her fans, the video can be read in 24 languages. There are thousands and thousands of comments below it, mostly positive. One reads, “Can you be my mom?”", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe8 = Recipe.create(title: "Rice Cake Soup With Dumplings", author_name: Faker::Kpop.solo, description: "Korean New Year, Solnal, is greeted with steaming bowls of rice cake soup called duk gook - \"comfort food,\" said Moon Sun Kwak, who serves it at Dok Suni and Do Hwa, her family\'s restaurants in Manhattan. Her mother, Myung Ja Kwak, who is the chef, slowly simmers beef bones into a marrow-rich broth as the base for the soup. \"It\'s so healthy,\" the elder Ms. Kwak said as she dropped homemade dumplings into the soup in Do Hwa\'s kitchen. Not all versions of the soup have dumplings; it\'s the duk, or rice cake slivers, that matter. \"You eat it so you can turn a year older.\"", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe9 = Recipe.create(title: "Vegetable Pajeon ", author_name: Faker::Kpop.solo, description: "Crisp at the edges, soft at the center and filled scallions and other vegetables, these irresistible, comforting pancakes (adapted from Sohui Kim of Insa and the Good Fork restaurants in Brooklyn) make for a quick dinner that you can throw together on any given weeknight. It’s extremely forgiving, so feel free to use whatever vegetables you have on hand. Ms. Kim recommends finely shredded raw vegetables, or even leftover cooked vegetables. And if you don’t have the bandwidth to make a dipping sauce, a drizzle of soy sauce and squirt of Sriracha adds verve without any work. Serve pajeon by itself or topped with a fried egg or two, if you want to add protein.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe10 = Recipe.create(title: "Brussels Sprouts with Kimchi", author_name: Faker::Kpop.solo, description: "Brussels sprouts offer tons of flavor on their own when charred properly, but their layered leaves also make them great for picking up other flavors. In this recipe, we pack the flavors in with kimchi, honey, and fish sauce. Roasting at very high heat caramelizes and chars the edges of the Brussels sprouts without allowing the insides to turn too soft. A balanced combination of tart and spicy kimchi, fish sauce, rice wine vinegar, and honey perfectly complements the nutty sweetness of Brussels sprouts.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe11 = Recipe.create(title: "Chicken Wings With Gochujang, Ginger and Garlic", author_name: Faker::Kpop.solo, description: "Wings have a higher ratio of skin to meat than almost any other cut of chicken, which is what makes them so appealing. In order to crisp the skin, you need to render out most of the fat that comes with it, otherwise you’ll get chewy wings instead of crunchy ones.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe12 = Recipe.create(title: "Coconut-Gochujang Glazed Chicken With Broccoli", author_name: Faker::Kpop.solo, description: "Gochujang, a staple of Korean cooking, is a fermented red chile paste made from spicy Korean chile peppers and glutinous rice. Here, it’s combined with coconut milk, which mellows the spicy gochujang into a creamy sauce. Fresh ginger is the key ingredient, infusing the sauce with brightness and spice that balance the rich coconut. This recipe calls for broccoli as the vegetable accompaniment, but cauliflower or brussels sprouts would also work. The sauce can be made in larger batches and used on grilled pork ribs, chicken wings or even pan-fried tofu.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe13 = Recipe.create(title: "Sheet-Pan Gochujang Chicken and Roasted Vegetables", author_name: Faker::Kpop.solo, description: "Gochujang, a Korean fermented chile paste, enlivens a straightforward dinner of roast chicken and vegetables with a salty, spicy and umami-rich layer of flavor. Freshly grated ginger, sliced scallions and quick-pickled radishes elevate the flavor even further. This recipe calls for a wintry mix of squash and turnips, but equal amounts of root vegetables like carrots, potatoes and beets, or lighter vegetables like cauliflower, brussels sprouts or broccoli will work well too. ", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe14 = Recipe.create(title: "Kimchi Soup", author_name: Faker::Kpop.solo, description: "In Korean cuisine, kimchi is not only a condiment or pickle; it is also used as an ingredient in many cooked dishes. Kimchi soup, called Jjigae, is a satisfying example. The fermented kimchi vegetables quickly provide deep flavor to the broth, so the soup can be produced in little more than half an hour. Aged kimchi, which is more intensely sour, is the preferred type to use. Surprisingly mellow, the soup is neither too spicy nor too salty.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe15 = Recipe.create(title: "Kimchi Noodle Cake", author_name: Faker::Kpop.solo, description: "This savory pan-fried noodle cake made with rice noodles (or leftover cooked spaghetti) packs a lot of flavor with just a few ingredients, ideal for a quick breakfast or lunch. The mixture can be assembled well in advance. It’s more steamed than fried, but a crisp bottom is revealed when the cake is flipped. Look for the red pepper paste (gochujang) at Korean markets.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe16 = Recipe.create(title: "Kimchi Fried Rice", author_name: Faker::Kpop.solo, description: "Not the high-heat stir-fry you might expect, Grace Lee’s home-style fried-rice recipe uses a simple technique — make an easy, flavorful kimchi sauce, mellowed out with butter, and sauté leftover rice in it. It\'s perfect for a snack or a quick, simple meal. The Spam, though optional, reflects many Koreans’ love of foods introduced by the American military.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe17 = Recipe.create(title: "Shrimp and Kimchi Rice Bowl", author_name: Faker::Kpop.solo, description: "If you want dinner with ease, make it a rice bowl. You can cook the rice in advance and reheat it, or employ a rice cooker. (A small one doesn’t demand much space, and it cooks perfect rice while you go about other business.) But even if you make rice on the stovetop, you’ll have 30 minutes to pull together the rest of this meal, so it’s hot and ready all at once. Kimchi is the heavy lifter here, since it has tons of crunch and tang, which gives you space to add in other vegetable without doing much to them. They could be grated and raw, or make use of yesterday’s leftovers. If shrimp isn’t your speed, try this marinade on beef chuck or tofu. Or top the rice with an egg fried in a mixture of canola and sesame oil.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe18 = Recipe.create(title: "Bo Ssam", author_name: Faker::Kpop.solo, description: "This is a recipe to win the dinner party sweepstakes, and at very low stakes: slow-roasted pork shoulder served with lettuce, rice and a raft of condiments. The chef David Chang serves the dish, known by its Korean name, bo ssam, at his Momofuku restaurant in the East Village and elsewhere. He shared the recipe with The Times in 2012. Mr. Chang is known as a kitchen innovator, but his bo ssam is a remarkably straightforward way to achieve high-level excellence with little more than ingredients and time. Simply cure the pork overnight beneath a shower of salt and some sugar, then roast it in a low oven until it collapses. Apply some brown sugar and a little more salt, then roast the skin a while longer until it takes on the quality of glistening bark. Meanwhile, make condiments – hot sauces and kimchi, rice, some oysters if you wish. Then tear meat off the bone and wrap it in lettuce, and keep at that until everything’s gone", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe19 = Recipe.create(title: "Roasted Vegetable Bibimbap", author_name: Faker::Kpop.solo, description: "The vegetarian cookbook author Lukas Volger has a way with Asian condiments and flavors. In this recipe for bibimbap, the egg-topped Korean rice bowl, he roasts squash, shiitakes and broccoli rabe in a sweet and spicy mix of soy, chile paste, sugar and oil. Mr. Volger crisps cooked rice in a skillet to get the characteristic crunch of bibimbap; you can prepare the rice up to three days ahead, but be sure to crisp it just before serving. If you want to skip that step, use freshly cooked rice instead.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe20 = Recipe.create(title: "Korean-Style Short Ribs", author_name: Faker::Kpop.solo, description: "This dish, known as galbi, is a fine thing to eat in a restaurant, but it also makes for a wonderful and easy meal at home. If you buy English-style short ribs, which are cut along the bone, you must butterfly the meat into a thin, long strip. If the ribs you buy are flanken-style, in which a band saw is used to cut across the ribs, creating half-inch slices of beef dotted with three little bones, rinse them under cold water before seasoning to remove any bone fragments. It’s a good idea to let the ribs marinate for at least two hours to allow the seasoning to penetrate; marinating overnight is even better.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe21 = Recipe.create(title: "Korean Rice Cakes With Red Chile Sauce", author_name: Faker::Kpop.solo, description: "This popular street-food dish, called tteokbokki, is a garlicky, richly spiced dish of rice cakes bathed in red chile paste. Tteokbokki (pronounced duck-bo-key) got its own festival, spinning off from the larger annual Seoul festival of rice cakes, or tteok.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe22 = Recipe.create(title: "Kimchi", author_name: Faker::Kpop.solo, description: "You don’t need stoneware crocks or special jars to make kimchi. You do need a large bowl and multiple containers. When you become confident, you can add radishes and turnips, but this is the basic formula, from a book on preserving, “Tart and Sweet” by Kelly Geary and Jessie Knadler. The carrots are not strictly traditional, but I particularly like their crunch. Some people like their kimchi “new,” and some let it get really funky. Refrigerated and covered, it lasts indefinitely. I eat it many ways: finely chopped with steamed rice, fried eggs and Japanese sesame salt; stirred into chicken noodle soup; on steak, mixed with fresh watercress. In Korean food, it’s ketchup, mustard and relish, all in one.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe23 = Recipe.create(title: "Mandoo (Korean Dumplings)", author_name: Faker::Kpop.solo, description: "Mandu (만두; 饅頭) are dumplings in Korean cuisine.[1][2] Mandu can be steamed, boiled, pan-fried, or deep-fried. The styles also vary across regions in Korean Peninsula.[3] Mandu were long part of Korean royal court cuisine, but are now found in supermarkets, restaurants, and snack places such as pojangmacha and bunsikjip throughout Korea.[4]", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe24 = Recipe.create(title: "Korean Fried Chicken", author_name: Faker::Kpop.solo, description: "Spicy Korean fried chicken, known as Yangnyeom Dak, became very popular in New York after it was introduced around 2006. Cecilia Hae-Jin Lee, the author of “Quick and Easy Korean Cooking,” said fried chicken became popular in Korea when fast-food places opened there after the war.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe25 = Recipe.create(title: "Jap Chae: Korean Noodles", author_name: Faker::Kpop.solo, description: "Japchae (잡채) literally means “mixed vegetables.” But the main ingredient of this classic dish is Korean sweet potato starch noodles (dangmyeon), also known as glass noodles. It’s an essential dish for traditional holidays and special occasions. There are many variations using different ingredients, as you can see from my Spicy Seafood Japchae and Kongnamul Japchae.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe26 = Recipe.create(title: "Korean Grilled Beef Lettuce Wraps", author_name: Faker::Kpop.solo, description: "This dish is downright addictive. Thinly-sliced strips of beef are marinated in a salty-sweet-spicy marinade then quickly seared on the grill. Then they\'re rolled up into ssam (Korean-style wraps) by folding a piece of steak or two, some rice, vegetables and herbs inside a crisp, cold lettuce leaf.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe27 = Recipe.create(title: "Braised Short-Rib Stew", author_name: Faker::Kpop.solo, description: "Here is an adaptation of the Korean braised-short-rib stew known as galbijjim, a staple of neighborhood potlucks and church suppers and, in the words of the Los Angeles chef Roy Choi, “that meal from home that every Korean kid says his or her mom does best.” His recipe (well, my version of his recipe, which is his version of his mom’s) is rich and deeply flavored, thickly sauced and pungent with sugar, spice, soy and garlic. It is the sort of meal you could put together on a weekend afternoon and serve for nights to come. It is the best sort of family food.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe28 = Recipe.create(title: "Spicy Korean Temple Noodles", author_name: Faker::Kpop.solo, description: "This dish, which clamors for a beer, is a simple tangle of noodles, each strand glossed with a ruddy, vibrant mix of seasonings. The method for cooking the noodles is unusual: very gentle and very effective. I’ll wager it works with angel hair.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))
recipe29 = Recipe.create(title: "Korean Acorn Jelly (Dotorimuk)", author_name: Faker::Kpop.solo, description: "Dotorimuk is made from acorns. Some people in Korea still make homemade dotorimuk from scratch, using acorns that they gathered or picked  from the mountain. The traditional way to make acorn jelly is to shell, dry, and powder the acorns, then mix them with water to remove the bitter and astringent taste. The starch will sink to the bottom, so the next day you should discard the bitter water on top and pour new water in. This is repeated for many days until  the starch is not bitter anymore. Then you make porridge with this starch mixture.", servings: Faker::Number.between(from: 2, to: 8) , min_duration: Faker::Number.between(from: 15, to: 180))

recipe1.photo.attach(io: File.open('app/assets/images/jajangmyeon.jpg'), filename: 'jajangmyeon.jpg')
recipe2.photo.attach(io: File.open('app/assets/images/scallion_pancakes.jpg'), filename: 'scallion_pancakes.jpg')
recipe3.photo.attach(io: File.open('app/assets/images/cold_noodles.jpg'), filename: 'cold_noodles.jpg')
recipe5.photo.attach(io: File.open('app/assets/images/mung_bean.jpg'), filename: 'mung_bean.jpg')
recipe6.photo.attach(io: File.open('app/assets/images/samgyetang.jpg'), filename: 'samgyetang.jpg')
recipe7.photo.attach(io: File.open('app/assets/images/fire_chicken.jpeg'), filename: 'fire_chicken.jpeg')
recipe8.photo.attach(io: File.open('app/assets/images/rice_cake_soup.jpg'), filename: 'rice_cake_soup.jpg')
recipe9.photo.attach(io: File.open('app/assets/images/veg_pancake.jpg'), filename: 'veg_pancake.jpg')
recipe10.photo.attach(io: File.open('app/assets/images/brussel.jpg'), filename: 'brussel.jpg')
recipe11.photo.attach(io: File.open('app/assets/images/garlic_wings.jpg'), filename: 'garlic_wings.jpg')
recipe12.photo.attach(io: File.open('app/assets/images/gochu_chicken.jpg'), filename: 'gochu_chicken.jpg')
recipe13.photo.attach(io: File.open('app/assets/images/gochu_sheet_chicken.jpg'), filename: 'gochu_sheet_chicken.jpg')
recipe14.photo.attach(io: File.open('app/assets/images/kimchi_soup.jpg'), filename: 'kimchi_soup.jpg')
recipe15.photo.attach(io: File.open('app/assets/images/kimchi_noodle.jpg'), filename: 'kimchi_noodle.jpg')
recipe16.photo.attach(io: File.open('app/assets/images/kimchi_fried_rice.jpg'), filename: 'kimchi_fried_rice.jpg')
recipe17.photo.attach(io: File.open('app/assets/images/shrimp_kimchi.jpg'), filename: 'shrimp_kimchi.jpg')
recipe18.photo.attach(io: File.open('app/assets/images/bo_ssam.jpg'), filename: 'bo_ssam.jpg')
recipe19.photo.attach(io: File.open('app/assets/images/veg_bibimbap.jpg'), filename: 'veg_bibimbap.jpg')
recipe20.photo.attach(io: File.open('app/assets/images/short_rib.jpg'), filename: 'short_rib.jpg')
recipe21.photo.attach(io: File.open('app/assets/images/rice_cakes.jpg'), filename: 'rice_cakes.jpg')
recipe22.photo.attach(io: File.open('app/assets/images/kimchi.jpg'), filename: 'kimchi.jpg')
recipe23.photo.attach(io: File.open('app/assets/images/mandoo.jpg'), filename: 'mandoo.jpg')
recipe24.photo.attach(io: File.open('app/assets/images/fried_chicken.jpg'), filename: 'fried_chicken.jpg')
recipe25.photo.attach(io: File.open('app/assets/images/japchae.jpg'), filename: 'japchae.jpg')
recipe26.photo.attach(io: File.open('app/assets/images/lettucewrap.jpg'), filename: 'lettucewrap.jpg')
recipe27.photo.attach(io: File.open('app/assets/images/kalbijjim.jpg'), filename: 'kalbijjim.jpg')
recipe28.photo.attach(io: File.open('app/assets/images/temple_noods.jpg'), filename: 'temple_noods.jpg')
recipe29.photo.attach(io: File.open('app/assets/images/acorn_jelly.jpg'), filename: 'acorn_jelly.jpg')

demo_id = User.find_by(email: "andhudhow@gmail.com").id

recipe_id = Recipe.first.id
while recipe_id <= Recipe.last.id
  
    10.times do
      Ingredient.create!(recipe_id: recipe_id, quantity: Faker::Number.between(from: 2, to: 8), description: ["cups", "tbs", "tsp", "grams"].sample + " " + Faker::Food.ingredient)
    end
    
    step = 1
    5.times do
      PrepStep.create!(recipe_id: recipe_id, step: step, description: prep_step_options.sample)
      step += 1
    end

    5.times do
      Comment.create!(recipe_id: recipe_id, user_id: (User.first.id..User.last.id).to_a.sample, body: comment_options.sample)
    end

    if recipe_id % 4 != 0
      RecipeSave.create!(recipe_id: recipe_id, user_id: demo_id)
    end

    #don't auto-seed for demo user (will do manually on site)
    user_id = User.first.id + 1

    while user_id < User.last.id
      Rating.create(recipe_id: recipe_id, user_id: user_id, star_rating: (3..5).to_a.sample)
      user_id += 1
    end
  
  recipe_id += 1
end

User.all.each do |user|
  icon = ['user-img-lime.png', 'user-img-eggplant.png', 'user-img-fish.png', 'user-img-tomato.png'].sample
  user.avatar.attach(io: File.open("app/assets/images/#{icon}"), filename: "#{icon}")
end